# Numpy Assignment

## Question 1:

In [20]:
# Write a NumPy program to test whether none of the elements of a given array is zero.


import numpy as np
x=np.array([1,2,3,4,5,6])
result=np.all(x!=0)
print(f"the array: {x}")
print(f"Is this array is a non zero array? {result}")

the array: [1 2 3 4 5 6]
Is this array is a non zero array? True


## Question 2:

In [7]:
# Write a NumPy program to test whether any of the elements of a given array is non-zero
import numpy as np
x=np.array([1,2,3,4,5,6,0])
result=np.any(x!=0)
print(f"the array: {x}")
print(f"Is this array elements contain a non zero element ? {result}")

the array: [1 2 3 4 5 6 0]
Is this array elements contain a non zero element ? True


## Question 3:

In [22]:
# Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given
import numpy as np
arr1=np.array([1,2,314.2,31,5])
arr2=np.array([11,2,314.7,0,5])
print(f"array 1 is: {arr1}")
print(f"array 2 is: {arr2}")
print("Element wise comparison (equal):")
equal_mask=(arr1==arr2)
if np.any(equal_mask):
  for (val1,val2) in zip(arr1[equal_mask],arr2[equal_mask]):
    print(f"array1: {val1}, array2: {val2}")
else:
  print("No equal elements")
print("Element wise comparison (with tolerance):")
close_mask=np.isclose(arr1,arr2,atol=0.5)
if np.any(close_mask):
  for (val1,val2) in zip(arr1[close_mask],arr2[close_mask]):
    print(f"array1: {val1}, array2: {val2}")
else:
  print("No equal elements with tolerance")







array 1 is: [  1.    2.  314.2  31.    5. ]
array 2 is: [ 11.    2.  314.7   0.    5. ]
Element wise comparison (equal):
array1: 2.0, array2: 2.0
array1: 5.0, array2: 5.0
Element wise comparison (with tolerance):
array1: 2.0, array2: 2.0
array1: 314.2, array2: 314.7
array1: 5.0, array2: 5.0


## Question 4

In [9]:
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
import numpy as np
zeros=np.zeros(10,dtype=int)
ones=np.ones(10,dtype=int)
fives=np.ones(10,dtype=int)*5
result =np.concatenate([zeros,ones,fives])
print("Array of 10 zeros, 10 ones and 10 fives")
print(result)

Array of 10 zeros, 10 ones and 10 fives
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


## Question 5

In [17]:
# Write a NumPy program to create an array of the integers from 30 to70.
import numpy as np
array=np.arange(30,71,dtype=int)
print('create an array of the integers from 30 to 70')
print(array)

create an array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## Question 6

In [19]:
#  Write a NumPy program to create a 3x3 identity matrix
import numpy as np
array=np.identity(3,dtype=int)
print("create a 3x3 identity matrix ")
print(array)

create a 3x3 identity matrix 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Question 7

In [25]:
# Write a NumPy program to generate a random number between 0 and 1
import numpy as np
num=np.random.random()
print('generate a random number between 0 and 1 ')
print(num)

generate a random number between 0 and 1 
0.5353301325049081


## Question 8

In [47]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
import numpy as np
num=np.random.randn(15)
print("generate an array of 15 random numbers")
print(num)


generate an array of 15 random numbers
[-0.73141268  0.36579997  2.14252894 -0.38800377  0.32724481 -1.84591809
  0.84829228 -0.02565057  0.08657861 -0.20230597  0.5917473  -0.14295066
  0.00505732  0.47627476 -0.20864692]


## Question 9

In [57]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
import numpy as np
v=np.arange(15,56)
print("create a vector with values ranging from 15 to 55 and print all values except the first and last")
print(v[1:-1])

create a vector with values ranging from 15 to 55 and print all values except the first and last
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


## Question  10

In [59]:
#  Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
import numpy as np
v=np.random.randint(0,10,5)
print("create a vector of length 5 filled with arbitrary integers from 0 to 10")
print(v)


create a vector of length 5 filled with arbitrary integers from 0 to 10
[5 4 9 1 1]


## Question 11

In [81]:
#  Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
import numpy as np
m=np.ones((10,10))
m[1:-1,1:-1]=0

print("create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.")
print(m)


create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Question 12

In [83]:
# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
import numpy as np
m=np.zeros((5,5),dtype=int)
np.fill_diagonal(m,np.arange(1,6))
print("create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.")
print(m)


create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5. 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## Question 13

In [1]:
#  Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
import numpy as np
m=np.zeros((4,4),dtype=int)
m[1::2,::2]=1
m[::2,1::2]=1
print("create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.")
print(m)

create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


## Question 14

In [2]:
# Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.
import numpy as np
arr1=np.array((1,2,3,4,5))
arr2=np.array((11,22,33,44,55))
np.savez("two_arrays.npz",f=arr1,t=arr2)
data = np.load('two_arrays.npz')
loaded_data1=data['f']
loaded_data2=data['t']
print(f"loaded array 1: {loaded_data1}")
print(f"loaded array 2: {loaded_data2}")

loaded array 1: [1 2 3 4 5]
loaded array 2: [11 22 33 44 55]


## Question 15

In [18]:
#  Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
import numpy as np
arr=np.random.randint(0,40,40)
print("create a one-dimensional array of forty pseudo-randomly generated values.")
print (arr)


create a one-dimensional array of forty pseudo-randomly generated values.
[23 15  1 18  6 22  7  0 13 11 35 22  3 28 14 20 11 10  0 20 32  2  4 27
  3 33 15 25 22 18 22 21 28  9 32 26  2 27 32 26]


## Question 16

In [19]:
#  Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
import numpy as np
arr=np.array((1,2,3,4,5))
print("a NumPy program to extract all numbers from a given array which are less and greater than a specified number.")
print(f"original array: {arr}")
threshold=3
less_than_threshold=arr[arr<threshold]
greater_than_threshold=arr[arr>threshold]
print(f"Elements less than threshold: {less_than_threshold}")
print(f"Elements greater than threshold: {greater_than_threshold}")



a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
original array: [1 2 3 4 5]
Elements less than threshold: [1 2]
Elements greater than threshold: [4 5]
